---
stages:
  - test
  - docker
  - acceptance

test:
  stage: test
  image: elixir:1.9
  services:
    - name: postgres:latest
      alias: postgres-test
  variables:
    POSTGRES_DB: database
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    MIX_ENV: test
  before_script:
    - apt-get update && apt-get -y install postgresql-client
    - ./scripts/init.sh
  script:
    - ./scripts/lint.sh
    - ./scripts/test.sh

docker:
  stage: docker
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

acceptance:
  image: cabify/challenge:latest
  stage: acceptance
  only:
    - master
  variables:
    POSTGRES_URL: postgres://puezvkdc:1QvjWdUoJHnXhShV7jgI1p7nXwlilIWn@raja.db.elephantsql.com:5432/puezvkdc
    PORT: "9091"
  services:
    - name: ${CI_REGISTRY_IMAGE}:latest
      alias: pooling
  script:
    - /harness --address http://pooling:${PORT} acceptance
